# Đổi dataset chỉ cần sửa file này

# ── CUBS Tech ──────────────────────────────────────────────────
dataset_dir:   "C:/Users/Admin/Desktop/Image Processing/DATASET_CUBS_tech"
image_subdir:   "images"
profile_subdir: "C:/Users/Admin/Desktop/Image Processing/DATASET_CUBS_tech/LIMA-Profiles/GT-FAMUS"
output_dir:     "C:/Users/Admin/Downloads/CUBS_DATSET/data/gt"     # null = <dataset_dir>/MASKS
ext:            ".tiff"
