# Đổi dataset chỉ cần sửa file này

# ── CUBS Tech ──────────────────────────────────────────────────
dataset_dir:   "C:/Users/Admin/Desktop/Image Processing/DATASET for Carotid Ultrasound Boundary Study (CUBS) an open multi-center analysis of computerized intima-media thickness measurement systems and their clinical impact/DATASET for Carotid Ultrasound Boundary Study (CUBS) an open multi-center analysis of computerized intima-media thickness measurement systems and their clinical impact"
image_subdir:   "IMAGES"
profile_subdir: "C:/Users/Admin/Desktop/Image Processing/DATASET for Carotid Ultrasound Boundary Study (CUBS) an open multi-center analysis of computerized intima-media thickness measurement systems and their clinical impact/DATASET for Carotid Ultrasound Boundary Study (CUBS) an open multi-center analysis of computerized intima-media thickness measurement systems and their clinical impact/SEGMENTATIONS/Manual-A1"
output_dir:     "C:/Users/Admin/Downloads/CUBS_DATSET/masks2"     # null = <dataset_dir>/MASKS
ext:            ".tiff"
